include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    library_prefixes: ignore
    no_leading_underscores_for_library_prefixes: ignore
    use_build_context_synchronously: ignore
formatter:
  trailing_commas: preserve
