library globals;

class Globals {
  //////////EN-US//////////
  static const String STRING_HOME_URL                                        = 'harmonoidservice.herokuapp.com';
  static const String STRING_INTERNET_ERROR                                  = 'Check your internet connection...';
  static const String STRING_SEARCH_HEADER                                   = 'Search Music';
  static const String STRING_SEARCH_MODE_SUBHEADER                           = 'What are you looking for ?';
  static const String STRING_OK                                              = 'OK';
  static const String STRING_YES                                             = 'YEA';
  static const String STRING_NO                                              = 'NO';
  static const String STRING_ALBUM                                           = 'Albums';
  static const String STRING_TRACK                                           = 'Tracks';
  static const String STRING_ARTIST                                          = 'Artists';
  static const String STRING_SEARCH_MODE_SUBTITLE_ALBUM                      = 'Search music from your favorite albums';
  static const String STRING_SEARCH_MODE_SUBTITLE_TRACK                      = 'Search for your favorite tracks';
  static const String STRING_SEARCH_MODE_SUBTITLE_ARTIST                     = 'Search music from your favorite artists';
  static const String STRING_SEARCH_HISTORY_SUBHEADER                        = 'Your recent searches';
  static const String STRING_SEARCH_RESULT_LOADER_LABEL                      = 'Getting your music...';
  static const String STRING_SEARCH_RESULT_TOP_SUBHEADER_ALBUM               = 'Here is the most close album from your request';
  static const String STRING_SEARCH_RESULT_TOP_SUBHEADER_TRACK               = 'Here is the most close track from your request';
  static const String STRING_SEARCH_RESULT_TOP_SUBHEADER_ARTIST              = 'Here is the artist of your request';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_0_ALBUM          = 'DOWNLOAD ALBUM';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_0_TRACK          = 'DOWNLOAD TRACK';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_0_ARTIST         = 'DOWNLOAD TRACKS';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_1_ALBUM          = 'SHOW ALBUM';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_1_TRACK          = 'SHOW TRACK';
  static const String STRING_SEARCH_RESULT_TOP_BUTTON_LABEL_1_ARTIST         = 'SHOW ARTIST';
  static const String STRING_SEARCH_RESULT_OTHER_SUBHEADER_ALBUM             = 'More albums from the result';
  static const String STRING_SEARCH_RESULT_OTHER_SUBHEADER_TRACK             = 'More tracks from the result';
  static const String STRING_SEARCH_RESULT_OTHER_SUBHEADER_ARTIST            = 'More similar artists';
  static const String STRING_ALBUM_VIEW_DOWNLOAD_BACK_TITLE                  = 'You cannot go back';
  static const String STRING_ALBUM_VIEW_DOWNLOAD_ERROR_TITLE                 = 'The track could not be saved';
  static const String STRING_ALBUM_VIEW_DOWNLOAD_ERROR_SUBTITLE              = 'We recommend you to check your internet connection and try again.';
  static const String STRING_ALBUM_VIEW_DOWNLOAD_BACK_SUBTITLE               = 'One or more tracks are being saved offline. Please wait until all the tracks are saved.';
  static const String STRING_ALBUM_VIEW_DOWNLOAD_DOUBLE_TITLE                = 'Wait';
  static const String STRING_ALBUM_VIEW_DOWNLOAD_DOUBLE_SUBTITLE             = 'This track is already being downloaded.';
  static const String STRING_ALBUM_VIEW_LOADER_LABEL                         = 'Getting tracks...';
  static const String STRING_ALBUM_VIEW_TRACKS_SUBHEADER                     = 'Here are the tracks from this album';
  static const String STRING_ALBUM_VIEW_INFO_SUBHEADER                       = 'Some insights of the album';
  static const String STRING_LOCAL_TOP_BODY_ALBUM_EMPTY                      = 'Search & save some music to see it here.';
  static const String STRING_LOCAL_TOP_SUBHEADER_ALBUM                       = 'Here is the latest album saved by you';
  static const String STRING_LOCAL_OTHER_SUBHEADER_ALBUM                     = 'Here are your other albums';
  static const String STRING_LOCAL_ALBUM_VIEW_TRACKS_SUBHEADER               = 'Here are the tracks you saved';
  static const String STRING_LOCAL_ALBUM_VIEW_INFO_SUBHEADER                 = 'Some insights of the album';
  static const String STRING_LOCAL_ALBUM_VIEW_ALBUM_DELETE_DIALOG_HEADER     = 'Delete this album ?';
  static const String STRING_LOCAL_ALBUM_VIEW_ALBUM_DELETE_DIALOG_BODY       = 'You surely wanna delete this...';
  static const String STRING_LOCAL_ALBUM_VIEW_TRACK_DELETE_DIALOG_HEADER     = 'Wanna delete this?';
  static const String STRING_LOCAL_ALBUM_VIEW_TRACK_DELETE_DIALOG_BODY       = 'Do you want to remove this track saved on your device?';
}