name: Github Actions
on: [push, pull_request]

jobs:
  build_windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          submodules: 'recursive'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - run: flutter config --enable-windows-desktop
      - run: flutter pub get
      - run: flutter build windows

      - uses: actions/upload-artifact@v1
        with:
          name: harmonoid-windows-exe
          path: build/windows/runner/Release

      - run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Harmonoid_InnoSetup.iss"
        shell: cmd
        # still need to sign it somehow

      - uses: actions/upload-artifact@v1
        with:
          name: harmonoid-windows-setup
          path: Output/harmonoid-setup.exe

      - run: flutter pub run msix:create --password ${{ secrets.PASSWORD }}
      - run: xcopy "build\windows\runner\Release\harmonoid.msix" "windows\msix\distribution\src"
      - uses: actions/upload-artifact@v1
        with:
          name: harmonoid-windows-msix
          path: windows/msix/distribution
